/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Sanker;
import forms.GostForms.NoviGostForm;
import forms.GostForms.PretragaGostaForm;
import forms.PorudzbinaForms.NovaPorudzbinaForma;
import forms.PorudzbinaForms.SvePorudzbineForma;
import forms.pice.NovoPiceForm;
import forms.pice.SvaPicaForm;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author 38169
 */
public class MainForm extends javax.swing.JFrame {

    Sanker ulogovani;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glavna forma");

        ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText(lblUlogovani.getText() + " " + ulogovani);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblUlogovani = new javax.swing.JLabel();
        mb = new javax.swing.JMenuBar();
        mPorudzbina = new javax.swing.JMenu();
        miNovaPorudzbina = new javax.swing.JMenuItem();
        miIzmeniPorudzbinu = new javax.swing.JMenuItem();
        mGost = new javax.swing.JMenu();
        miNoviGost = new javax.swing.JMenuItem();
        miPretragaGosta = new javax.swing.JMenuItem();
        mPice = new javax.swing.JMenu();
        miNovoPice = new javax.swing.JMenuItem();
        miSvaPica = new javax.swing.JMenuItem();
        mOdjava = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani korisnik:");

        mPorudzbina.setText("Porudzbina");

        miNovaPorudzbina.setText("Nova porudzbina");
        miNovaPorudzbina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaPorudzbinaActionPerformed(evt);
            }
        });
        mPorudzbina.add(miNovaPorudzbina);

        miIzmeniPorudzbinu.setText("Izmeni porudzbinu");
        miIzmeniPorudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzmeniPorudzbinuActionPerformed(evt);
            }
        });
        mPorudzbina.add(miIzmeniPorudzbinu);

        mb.add(mPorudzbina);

        mGost.setText("Gost");

        miNoviGost.setText("Novi gost");
        miNoviGost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviGostActionPerformed(evt);
            }
        });
        mGost.add(miNoviGost);

        miPretragaGosta.setText("Pretraga gosta");
        miPretragaGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaGostaActionPerformed(evt);
            }
        });
        mGost.add(miPretragaGosta);

        mb.add(mGost);

        mPice.setText("Pice");

        miNovoPice.setText("Novo pice");
        miNovoPice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoPiceActionPerformed(evt);
            }
        });
        mPice.add(miNovoPice);

        miSvaPica.setText("Pregled pica");
        miSvaPica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSvaPicaActionPerformed(evt);
            }
        });
        mPice.add(miSvaPica);

        mb.add(mPice);

        mOdjava.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        mOdjava.add(miOdjava);

        mb.add(mOdjava);

        setJMenuBar(mb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovaPorudzbinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaPorudzbinaActionPerformed
        NovaPorudzbinaForma forma = new NovaPorudzbinaForma(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miNovaPorudzbinaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int odgovor= JOptionPane.showConfirmDialog(this,
                "Da li ste sigurni da zelite da se odjavite?", 
                "Odjava",
                JOptionPane.YES_NO_OPTION);
        
        if(odgovor==JOptionPane.NO_OPTION) return;
        else if(odgovor==JOptionPane.YES_OPTION) {
            Session.getInstance().setUlogovani(null);
            LoginForm lf= new LoginForm();
            lf.setVisible(true);
                 
            this.dispose();
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNoviGostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviGostActionPerformed
        NoviGostForm forma= new NoviGostForm(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miNoviGostActionPerformed

    private void miPretragaGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaGostaActionPerformed
         PretragaGostaForm forma= new PretragaGostaForm(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miPretragaGostaActionPerformed

    private void miNovoPiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoPiceActionPerformed
        NovoPiceForm forma= new NovoPiceForm(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miNovoPiceActionPerformed

    private void miSvaPicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSvaPicaActionPerformed
        SvaPicaForm forma= new SvaPicaForm(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miSvaPicaActionPerformed

    private void miIzmeniPorudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniPorudzbinuActionPerformed
        SvePorudzbineForma forma= new SvePorudzbineForma(this, true);
        forma.setVisible(true);
    }//GEN-LAST:event_miIzmeniPorudzbinuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenu mGost;
    private javax.swing.JMenu mOdjava;
    private javax.swing.JMenu mPice;
    private javax.swing.JMenu mPorudzbina;
    private javax.swing.JMenuBar mb;
    private javax.swing.JMenuItem miIzmeniPorudzbinu;
    private javax.swing.JMenuItem miNovaPorudzbina;
    private javax.swing.JMenuItem miNoviGost;
    private javax.swing.JMenuItem miNovoPice;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaGosta;
    private javax.swing.JMenuItem miSvaPica;
    // End of variables declaration//GEN-END:variables
}
